### ISSUE TITLE
Problems browsing empty repository

### ISSUE THREAD

**Issue by simonstearn1** [pplr/redmine-libsvn#5]
Causes a server error when browsing a repository from redmine 0.9.2 if the repository is new / has no files checked in.  Checking in a file fixes this issue. It seems to be caused by calling a revision 1 which doesnt yet exist.

**Comment by panga** [comment]
I have the same problem. I fixed this and I posted the issue #3.

"The plugin doesn't have catch exception in the method "def revisions", when the RedMine fetch a changeset of a non root directory, the ruby svn bindings returns an exception because the path doesn't exists in that revision.

To fix, i add the line "rescue" at the end of method "def revisions".

def revisions
... + rescue end"

**Comment by pplr** [comment]
I cannot reproduce this bug. Neither fetch_changeset method nor browsing the repository raises an exception. Here is the procedure I followed :
1. created a new empty repository with "svnadmin create /path-to-repo"
2. created a new redmine project with "file:///path-to-repo" as repository url
3. clicked on "Repository" tab

I fixed issue #3. Did it also fix this issue ?

**Comment by simonstearn1** [comment]
I still see the problem - I am using apache with the svn mod rather than a file based repository.  Will do some more analysis during a quiet time in a few days and post back what I find.
